export const errorCode = {
  BAD_REQUEST: 'BAD_REQUEST',
  URI_NOT_FOUND: 'URI_NOT_FOUND',
  NOT_FOUND: 'NOT_FOUND',
  HOLD_CASH_OVERNIGHT: 'HOLD_CASH_OVERNIGHT',
  NOT_APPROVED_BAG: 'NOT_APPROVED_BAG',
  UNAUTHORIZED: 'UNAUTHORIZED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  VALIDATION: 'VALIDATION'
}
